% Export a small ordinary Alcubierre reference case from MATLAB WarpFactory.
%
% Run this from the pyWarpFactory repository root after adding the original
% WarpFactory MATLAB folders to the MATLAB path if they are not already there.
% The default parameters mirror examples/verify_alcubierre_warpfactory.py.

clear variables;

gridSize = [5, 20, 20, 20];
gridScale = [1, 0.2, 0.2, 0.2];
worldCenter = [1, gridScale(2) * gridSize(2) / 2, gridScale(3) * gridSize(3) / 2, gridScale(4) * gridSize(4) / 2];
v = 0.5;
R = 1.4;
sigma = 5.0;
numVecs = 12;

Metric = metricGet_Alcubierre(gridSize, gridScale, worldCenter, v, R, sigma);
[Energy, EnergyEulerianTensor] = solveGet_EnergyTensor(Metric, gridScale);

NullMap = analyzeEnergyConditions(EnergyEulerianTensor, "Null", numVecs);
WeakMap = analyzeEnergyConditions(EnergyEulerianTensor, "Weak", numVecs);
StrongMap = analyzeEnergyConditions(EnergyEulerianTensor, "Strong", numVecs);
DominantMap = analyzeEnergyConditions(EnergyEulerianTensor, "Dominant", numVecs);

MetricTensor = Metric.tensor;
EnergyTensor = Energy.tensor;

outputPath = fullfile("tools", "alcubierre_reference.mat");
save( ...
    outputPath, ...
    "MetricTensor", ...
    "EnergyTensor", ...
    "EnergyEulerianTensor", ...
    "NullMap", ...
    "WeakMap", ...
    "StrongMap", ...
    "DominantMap", ...
    "gridSize", ...
    "gridScale", ...
    "worldCenter", ...
    "v", ...
    "R", ...
    "sigma", ...
    "numVecs", ...
    "-v7.3" ...
);

fprintf("Saved Alcubierre WarpFactory reference to %s\n", outputPath);
